// src/pages/frontend/NewsDetail.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import DateFormatter from '@/components/common/DateFormatter';
import { getNewsByIdNoUser } from '@/services/frontend/newsService';
import { getImageUrl } from '@/utils/ImageUtils';
import { MdShare } from 'react-icons/md';

const NewsDetail: React.FC = () => {
  const { newsUid } = useParams<{ newsUid: string }>();
  const [newsItem, setNewsItem] = useState<any | null>(null);

  const fetchNewsDetail = async (uid: string) => {
    try {
      const { success, data, message } = await getNewsByIdNoUser(uid);
      if (success) {
        setNewsItem(data);
      } else {
        console.error('Error fetching news:', message);
      }
    } catch (error) {
      console.error('Error fetching news detail:', error);
    }
  };

  useEffect(() => {
    if (newsUid) {
      fetchNewsDetail(newsUid);
    }
  }, [newsUid]);

  if (!newsItem) return <p className="news-detail__loading">Loading...</p>;

  return (
    <div className="news-detail">
      <div className="news-detail__header">
        <div>
          <h1 className="news-detail__title">{newsItem.title}</h1>
          <p className="news-detail__date">
            <DateFormatter date={newsItem.createdDate} format="YYYY.MM.DD" />
          </p>
        </div>
      </div>

      <div className="news-detail__card">
        <img
          className="news-detail__image"
          src={getImageUrl(newsItem.imageUrl)}
          alt={newsItem.title}
        />
        {newsItem.preview && (
          <div
            className="news-detail__preview"
            dangerouslySetInnerHTML={{ __html: newsItem.preview }}
          />
        )}
        {newsItem.content && (
          <div
            className="news-detail__content"
            dangerouslySetInnerHTML={{ __html: newsItem.content }}
          />
        )}
      </div>
    </div>
  );
};

export default NewsDetail;

// src/views/front/NewsDetail.vue
<template>
  <div class="news-detail">
    <div class="news-detail__container">
      <h1 class="news-detail__title">{{ detail?.title }}</h1>
      <p class="news-detail__date">
        <DateFormatter :date="detail?.createdDate" :format="'YYYY.MM.DD'" />
      </p>
      <img
        v-if="detail?.imageUrl"
        :src="getImageUrl(detail.imageUrl)"
        class="news-detail__image"
        :alt="detail?.title"
      />
      <div
        class="news-detail__content"
        v-html="formatContent(detail?.content)"
      ></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import { getNewsByIdNoUser } from '@/services/newsService';
import { getImageUrl } from '@/utils/ImageUtils';
import DateFormatter from '@/components/common/DateFormatter.vue';
const route = useRoute();
const detail = ref<any>(null);

const fetchDetail = async () => {
  const id = route.params.id as string;
  try {
    const res = await getNewsByIdNoUser(id);
    if (res.success) {
      detail.value = res.data;
    }
  } catch (error) {
    console.error('取得新聞詳情失敗', error);
  }
};

const formatDate = (dateStr?: string) => {
  if (!dateStr) return '';
  const date = new Date(dateStr.replace(/-/g, '/'));
  return `${date.getFullYear()}.${date.getMonth() + 1}.${date.getDate()}`;
};

const formatContent = (text?: string) => {
  return text?.replace(/\n/g, '<br/>') ?? '';
};

onMounted(fetchDetail);
</script>

<style scoped lang="scss">
.news-detail {
  color: #01befe;
  min-height: 100vh;
  padding: 2rem 1rem;

  &__container {
    max-width: 900px;
    margin: 0 auto;
    background-color: transparent;
    text-align: center;
  }

  &__title {
    font-size: 1.5rem;
    font-weight: 700;
    color: #01befe;
    text-align: left;
    margin-bottom: 0.25rem;
    letter-spacing: 0.05em;

    @media (min-width: 768px) {
      font-size: 2rem;
    }
  }

  &__date {
    text-align: left;
    font-size: 0.85rem;
    color: #01befe;
    margin-bottom: 1.5rem;
    letter-spacing: 0.05em;
  }

  &__image {
    max-width: 100%;
    height: auto;
    margin-bottom: 1.5rem;
    border-radius: 8px;
    box-shadow: 0 0 8px rgba(0, 0, 0, 0.3);
  }

  &__content {
    text-align: left;
    line-height: 1.6;
    font-size: 1rem;
    white-space: pre-wrap;

    @media (min-width: 768px) {
      font-size: 1.05rem;
    }
  }
}
</style>
